name: Pipeline CI/CD

on:
  push:
    branches:
      - main

jobs:
  validar_codigo:
    name: Validar Código
    runs-on: ubuntu-latest

    steps:
      - name: Baixar repositório
        uses: actions/checkout@v4

      - name: Verificar arquivos
        run: |
          echo "Validando arquivos do projeto..."
          ls
          echo "Validação concluída!"

  build_projeto:
    name: Simular Build
    runs-on: ubuntu-latest
    needs: validar_codigo

    steps:
      - name: Baixar repositório
        uses: actions/checkout@v4

      - name: Criar pasta dist
        run: mkdir dist

      - name: Copiar arquivos
        run: |
          cp *.html dist/
          cp *.css dist/

      - name: Mostrar secret
        run: echo "Mensagem secreta: ${{ secrets.MENSAGEM_SECRETA }}"