name: Pipeline CI/CD

on:
  push:
    branches:
      - main

jobs:
  validar_codigo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Validar arquivos
        run: |
          echo "Validando projeto..."
          ls
          echo "Validação concluída"

  build_projeto:
    runs-on: ubuntu-latest
    needs: validar_codigo

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Criar pasta dist
        run: mkdir dist

      - name: Copiar arquivos
        run: |
          cp *.html dist/ || true
          cp *.css dist/ || true

      - name: Mostrar secret
        run: "echo Mensagem secreta: ${{ secrets.MENSAGEM_SECRETA }}"